import { CampaignGoal } from './campaign.models';

/**
 * Per-channel settings from Advanced Options
 */
export interface ChannelSettings {
  channelId: string;
  enabled: boolean;
  minPercent: number;
  maxPercent: number;
  cpmOverride?: number;       // Optional: override default CPM
  frequencyOverride?: number; // Optional: override default frequency
}

/**
 * Complete planner input (frontend-only calculation)
 */
export interface PlannerInput {
  totalBudget: number;
  durationDays: number;
  goal: CampaignGoal;
  globalMinPercent: number;
  globalMaxPercent: number;
  channelSettings: ChannelSettings[];
  // For Video/Display slider adjustment
  videoDisplayBias?: number;  // -50 to +50, positive = more video
}

/**
 * Validation result
 */
export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Single channel allocation result
 */
export interface ChannelAllocationResult {
  channelId: string;
  percentage: number;
  budget: number;
  dailyBudget: number;
  cpmUsed: number;
  frequencyUsed: number;
  impressions: number;
  reach: number;
  dailyImpressions: number;
  isConstrained: 'none' | 'min' | 'max';
  score: number;
}

/**
 * Complete planner result
 */
export interface PlannerResult {
  allocations: ChannelAllocationResult[];
  summary: {
    totalBudget: number;
    durationDays: number;
    dailyBudget: number;
    totalImpressions: number;
    totalReach: number;
    averageCPM: number;
    goal: CampaignGoal;
  };
  insights: PlannerInsight[];
  calculatedAt: Date;
}

/**
 * Insight/warning generated by planner
 */
export interface PlannerInsight {
  type: 'warning' | 'info' | 'tip';
  icon: string;
  title: string;
  message: string;
}

/**
 * Saved scenario for comparison
 */
export interface SavedScenario {
  id: string;
  name: string;
  savedAt: Date;
  input: PlannerInput;
  result: PlannerResult;
}

